# -*- coding: utf-8 -*-
"""PigLatin#1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G6ey_MozpnGscKq2_p7wvTFS0A1dVrTJ
"""

pyg = 'ay'


original = input('Enter a word: ')


if len(original) > 0 and original.isalpha():

  word = original.lower()

  first = word[0]

  new_word = word + first + pyg

  new_word = new_word[1:len(new_word)]

  print(new_word)

else:

  print("empty")

  # Looks neat

